language: node_js

os:
 - linux

node_js:
 - "10.15.1"

branches:
  only:
    - main

jobs:
  include:
    - stage: "Release"
      name: "Generate a new Release"
      if: (branch = main) AND (NOT (type = pull_request))
      script: echo \"Skipping second test execution but keeping NPM hooks alive.\"
      deploy:
         provider: script
         skip_cleanup: true
         script:
          - npx semantic-release
    - stage: "API Generation"
      script:
        - LAST_RELEASED_VERSION=$(npm view $(node -p "require('./package.json').name") version) npm run docs
