language: node_js

os:
 - linux

node_js:
 - "10.15.1"

branches:
  only:
    - master

jobs:
  include:
    - stage: "Release"
      name: "Generate a new Release"
      if: (branch = master) AND (NOT (type = pull_request))
      script: echo \"Skipping second test execution but keeping NPM hooks alive.\"
      deploy:
         provider: script
         skip_cleanup: true
         script:
          - npx semantic-release
      after_deploy: export NPM_PACKAGE_VERSION=$(npm --silent run node -- --print process.env.npm_package_version) && echo $NPM_PACKAGE_VERSION
    - stage: "API Generation"
      script: export npm_package_version=$NPM_PACKAGE_VERSION && npm run printVersion