name: Pull Request Voting

on:
  pull_request:
    branches:
      - master
jobs:
  build:
     name: Checks and Tests
     runs-on: ubuntu-latest
     if: "!contains(github.event.head_commit.message, '[skip ci]')"
     steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Install dependencies
        run: npm install
      - name: JSLint Checks
        run: npm run lint
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}