name: Checks and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  
  build:
     name: Build
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Install dependencies
        run: npm install
      - name: JSLint Checks
        run: npm run lint
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}