name: Continous Integration

on:
  pull_request:
    branches:
      - master
jobs:
  build:
     name: Build, Lint Checks and Tests
     runs-on: ubuntu-latest
     steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout  
        uses: actions/checkout@v2
      - name: Setup Node 
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Install NPM dependencies
        run: npm install
      - name: Setup Java 
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true
      - name: Setup Docker 
        uses: docker-practice/actions-setup-docker@master
      - name: Start Mock Server 
        shell: bash
        run: |
         chmod +x "${GITHUB_WORKSPACE}/scripts/setup_mock.sh"
         "${GITHUB_WORKSPACE}/scripts/setup_mock.sh"
      - name: JSLint
        run: npm run lint
      - name: Tests
        run: npm run test  
