name: Continous Integration

on:
  pull_request:
    branches:
      - master
jobs:
  build:
     name: Build, Lint Checks and Tests
     runs-on: ubuntu-latest
     steps:
      - name: Checkout  
        uses: actions/checkout@v2
      - name: Setup Node 
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Setup Java 
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true
      - name: Setup Docker 
        uses: docker-practice/actions-setup-docker@master
        run: docker version
      - name: Download Hapi Repo  
        uses: actions/checkout@v2
        with:
          repository: 'https://github.com/hapifhir/hapi-fhir-jpaserver-starter'
          ref: '38c711dabfa5433036a949be639b769f47d122c9'
      - name: Install NPM dependencies
        run: npm install
      - name: JSLint
        run: npm run lint
      - name: Tests
        run: npm run test  
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}